name: integration-test

on:
  push:
    branches: [ master, 2.4 ]
  pull_request:
    branches: [ master, 2.4 ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Start clickhouse-server
        run: docker-compose up -d
      - name: Run integration tests with Scala 2.11 & Spark 2.4.7
        run: mvn -B clean verify
      - name: upload code coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
      - name: Run integration tests with Scala 2.12 & Spark 2.4.7
        run: mvn clean package -pl :clickhouse-integration-spark_2.12 -am -Pscala-2.12
      - name: Run integration tests with Scala 2.12 & Spark 3.0.1
        run: mvn clean package -pl :clickhouse-integration-spark_2.12 -am -Pscala-2.12 -Dspark.version=3.0.1

